### ISSUE TITLE
Double scroll bars on Chromium Edge

### ISSUE THREAD

**Issue by fxzxmicah** [bitwarden/browser#1030]
Double scrollbars will appear after installation. 
![image](https://user-images.githubusercontent.com/48860358/66319656-175ae880-e950-11e9-95c0-deab72de5e14.png)

**Comment by fxzxmicah** [comment]
By the way, there is no certificate in the appx installation file, which makes it impossible for me to install the edge extension. I hope you can fix it, or update the version in the Microsoft store.

**Comment by Ezzahhh** [comment]
I am getting this issue on: 78.0.3904.70 (Official Build) (64-bit) on MacOS 10.15

**Comment by fxzxmicah** [comment]
No, this browser extension has this problem on all pages, not just special pages. @Ezzahhh

**Comment by Ezzahhh** [comment]
I believe it may be something to do with browser default zoom. Is it greater than 100%? @fxzxmicah

**Comment by fxzxmicah** [comment]
Oh, that's it. Thank you. But can't you change it so that it's not affected by browser scaling? After all, I still like to use zoom. And a browser plug-in should not need scaling. @Ezzahhh

**Comment by Ezzahhh** [comment]
Yeah I think that should be fixed, but it is a temporary solution @fxzxmicah

**Comment by fxzxmicah** [comment]
OK, thank you and look forward to your next version.

**Comment by DustyDuster** [comment]
This problem still persist, brave browser
![bw](https://user-images.githubusercontent.com/57709350/106363231-fcc03600-632f-11eb-933e-efe92cff2d6c.png)
