### ISSUE TITLE
Firefox addon popup menu differs in size

### ISSUE THREAD

**Issue by internetuser2** [bitwarden/browser#1451]
## Describe the Bug

The height of the Firefox addon popup menu is different in height depending on how/when you click on the Bitwarden icon to open the menu.

## Steps To Reproduce

1. Click once on the Bitwarden icon to open the menu. You'll notice that the menu is not very tall.
2. Without moving the mouse away click the icon again to close the menu.
3. Now still keep the mouse hovering over the icon. Click the icon again to open the menu yet again. This time the menu is the normal/correct height.
4. Move the mouse cursor away and click somewhere outside the popup to make the popup close. 
5. Open the popup menu again. The size of the popup is small again.

## Expected Result

The popup menu should always be the same size.

## Actual Result

The popup menu is sometimes smaller then expected. It shows less information and makes working with it (especially when editing items) a bit more difficult.

## Screenshots or Videos

The "wrong" height: https://i.ibb.co/hsGbShX/bitwarden.jpg
Screen recording of the issue: https://i.ibb.co/dsvnZhh/bw.gif

## Environment

- Operating system: macOS High Sierra (10.13.6)
- Browser: Firefox 82.0.2 (64-bit)
- Bitwarden Firefox addon: Version 1.46.2
- Bitwarden macOS app: Version 1.22.2 (1.22.2)

Other acive Firefox addons:
- uBlock Origin
- uMatrix
- Privacy Settings (https://add0n.com/privacy-settings.html)
- HTTPS Everywhere
- Web Developer (https://chrispederick.com/work/web-developer/)

---

Ref: https://www.reddit.com/r/Bitwarden/comments/jnzw62/change_height_of_firefox_addon_popup/

**Comment by fifal** [comment]
I have exactly the same issue.

Browser: Firefox 84.0.1
Bitwarden Firefox addon: 1.47.1

**Comment by pwyde** [comment]
I can also confirm this issue.

- OS; Arch Linux
- Browser: Firefox 84.0.2 (64-bit)
- Bitwarden Firefox extension: 1.47.1

Other active Firefox extensions:

- Cookie AutoDelete 3.5.1
- Dark Reader 4.9.26
- Decentraleyes 2.0.15
- Facebook Container 2.1.2
- Firefox Multi-Account Containers 7.1.0
- HTTPS Everywhere 2020.11.17
- uBlock Origin 1.32.4

**Comment by fifal** [comment]
I managed to resolve this issue.

I have restored Firefox to [default settings](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) and after that the issue never occured again.

I'm not sure if this helps anybody else but I guess it is worth a try.

**Comment by pwyde** [comment]
In my humble opinion it is not a solution to reset to default settings. I would not even call it a workaround. As a Firefox user I should be able to run it with my preferred settings, wether it is in extensions or Firefox itself. It would be a shame having to nuke all settings just to resolve this issue.

I do however acknowledge that some advanced settings might be conflicting with the Bitwarden extension. Hence I did some investigation on my system. 

I found that the setting **privacy.resistFingerprinting** = `true` causes this behaviour. According to [privacytools](https://privacytools.io/browsers/#about_config) this should be set to `true` to achieve better online privacy. Setting this to the default of `false` resolved the issue for me.

It is not totally unlikely that the extension [Privacy Settings](https://addons.mozilla.org/en-US/firefox/addon/privacy-settings/) (that OP uses) modifies this advanced setting or some other setting which causes this behaviour of Bitwarden extension in Firefox.

**Comment by fifal** [comment]
I can confirm that **privacy.resistFingerprinting** causes this issue.

>In my humble opinion it is not a solution to reset to default settings. I would not even call it a workaround. As a Firefox user I should be able to run it with my preferred settings, wether it is in extensions or Firefox itself. It would be a shame having to nuke all settings just to resolve this issue.

After I restored Firefox to default settings I synced the settings using Firefox account, but I didn't know it does not sync the custom changes made in `about:config`, my bad.

**Comment by internetuser2** [comment]
> I found that the setting **privacy.resistFingerprinting** = `true` causes this behaviour. According to [privacytools](https://privacytools.io/browsers/#about_config) this should be set to `true` to achieve better online privacy. Setting this to the default of `false` resolved the issue for me.
> 
> It is not totally unlikely that the extension [Privacy Settings](https://addons.mozilla.org/en-US/firefox/addon/privacy-settings/) (that OP uses) modifies this advanced setting or some other setting which causes this behaviour of Bitwarden extension in Firefox.

Great find and yes, I do have that option enabled through that extension:

![Screen Shot 2021-01-12 at 16 31 30](https://user-images.githubusercontent.com/74061282/104335749-ff2f2d00-54f3-11eb-858d-5398a608c0df.jpg)

**Comment by alexmehta** [comment]
Resist fingerprinting was the issue for me.

**Comment by binnih** [comment]
I have the same problem. Is the same in Firefox on Linux and Mac.

**Comment by setyb** [comment]
The reason this likely happens is because the `resistFingerprinting` intentionally changes the reported screen size in order to... you guessed it... *resist fingerprinting*.

This is because fingerprinters often use your screen dimensions to add additional bits to your profile for tracking purposes.

It may be possible for Bitwarden to accommodate for this **intentional obfuscation**, but the challenge is that the data Bitwarden is receiving is *intentionally* incorrect in order to reduce the effectiveness of any tracking code.

I do wonder if it's overkill for Firefox to obfuscate data being given to web extensions, as if you're running rogue code within a web extension, your problems are much bigger than fingerprinting.  If anyone agrees, you can file an issue report with Mozilla to see if their engineers also agree.

**Comment by internetuser2** [comment]
> The reason this likely happens is because the `resistFingerprinting` setting _intentionally_ changes the reported screen size in order to... you guessed it... _resist fingerprinting_.

Yes, it must have something to do with this. The strange thing is that if you don't move your mouse away from the Bitwarden toolbar icon and click it again (to close the popup) and again (to open the popup again) the size of the popup is correct and will stay correct as long as you don't move our mouse off the icon.

**Comment by setyb** [comment]
> Yes, it must have something to do with this. The strange thing is that if you don't move your mouse away from the Bitwarden toolbar icon and click it again (to close the popup) and again (to open the popup again) the size of the popup is correct and will stay correct as long as you don't move our mouse off the icon.

I'm *guessing* that's because the user hasn't triggered anything that will cause the `resistFingerprinting` code to change the reported viewport size.  It's actually an interesting discovery, and you may want to notify the good people over at Mozilla just to let them know.

**Comment by kapitainsky** [comment]
Interestingly on macOS changing ResistFingerprinting to true does not lead to BW extension windows size change but makes extension always display in Light mode regardless of what mode (Light/Dark) Firefox is using.

**Comment by sergei1152** [comment]
Seeing this as well on the latest firefox build (99.0) on MacOS (m1 macbook)

**Comment by helpthemfix** [comment]
> Seeing this as well on the latest firefox build (99.0) on MacOS (m1 macbook)

Me too. This issue is very annoying.

**Comment by T-D3V** [comment]
Yeah this Issue still persists and is very anoying

**Comment by dwbit** [comment]
Thanks for the feedback everyone, we're looking into it. For now, please keep in mind that fingerprinting in Firefox is currently an experimental feature and may change at any time. Setting the experimental feature to false does resolve the issue.

**Comment by pohutukawa** [comment]
Discovered this a couple of weeks ago on my Brave on Linux browser, too. It would be really good if either the underlying issue of resolution dependency could be fixed or a manual setting provided to self-adjust the sizing in the options.

**Comment by broady02** [comment]
Hi! My Brave browser started doing this recently, driving me crazy! Thanks to previous comments I found a workaround.
In brave://flags/ search fingerprint and disable "Block screen fingerprinting".

Perhaps instead of trying to adjust the size of the screen, we could have an option to resize and remember the last size used.
It's completely understandable others may not want to disable this.

**Comment by Nokel81** [comment]
This has started happening to me even if I don't have `resistFingerprinting` turned on. I am running macOS firefox with several external monitors of differing sizes and resolutions plugged in.

**Comment by rallyemax** [comment]
In my case, the behavior is _worse_ when `resistFingerprinting` is `false` in a multi-monitor setup under Wayland.

When it's `true`, I can get the window to resize to full height by clicking it twice.

But when it's `false`, it stays small regardless of how many times I click it.

`screen.availHeight` is reported as 1216 (internally in the console and externally when checked with something like [amiunique.org](url)). Anything above 800 pixels ought to be normal height according to [apps/browser/src/popup/services/init.service.ts](https://github.com/bitwarden/clients/blob/7fbfce953d28a40d8e7bdb8b32fa154ac8b40672/apps/browser/src/popup/services/init.service.ts)

When the external monitor is unplugged, the window appears in its normal, larger height. `availHeight` does not change when this happens, so the plugin must be looking at some other attribute. It feels like it's performing its own calculation based on total available geometry. My monitors are stacked one above the other, here are the geometries:
  - external (top): 1920x1080
  - internal (bottom): 2736x1824 with 1.5 scaling, yielding 1824x1216

No change in behavior (still small popup window) if I reorient the screens so that they are side by side though.

System info:
  - ArchLinux with kernel v6.1.4
  - KDE  Plasma 5.26
  - Firefox 108.0.2, in Wayland mode using `MOZ_ENABLE_WAYLAND=1`
  - Bitwarden extension version 2022.12.1.

**Comment by julienkosinski** [comment]
I can reproduce this issue on Firefox on Wayland in my Fedora on KDE.
I cannot reproduce this size problem with widgets for other extensions, so I believe this might be a specific bug regarding Bitwarden Firefox Extension. I can confirm there's no working workaround with piracy settings.

I have to add that I use fractional scaling and KDE and that `widget.wayland.fractional-scale.enabled` is set to `false` (this is the default setting) as setting it to `true` make everything even worse. I can provide a screenshot with this setting on if needed but I'm not sure it's relevant.

**Comment by alyandon** [comment]
I have this problem on Firefox Developer edition on MacOS.  I do not have resist fingerprinting enabled.  For me, disabling advanced tracking protection on a site appears to fix it on that site.

**Comment by Eosxx** [comment]
It happen to me on Firefox for MaxOs.
Seting `resistFingerprinting = true` solved it.

**Comment by BWPeter** [comment]
Closing this issue as it appears the originally posted problem has been resolved. A mitigation has been implemented in the QA environments and will be released on May 29th. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Comment by dumbu3** [comment]
The problem is still there for me.
Im using Librewolf with the following Config:

- Enable ResistFingerprinting
- Enable letterboxing

if i press 2 times CTRL+L It comes as "popup"

https://streamable.com/mni2a7

**Comment by brendonrapp** [comment]
I am experiencing this on Firefox Dev Edition 143.b05.

I noticed that the speed in which I click the extension icon matters. If I hold the click a little longer before releasing, the menu opens full size. If I release quickly, the menu opens small (or more accurately opens at full size for a brief flash, then shrinks to the shortened size).

**Comment by dotter-ak** [comment]
Same issue for me (FF 143.0.1)

**Comment by alyandon** [comment]
Still present for me as well on latest FF 144 dev.  I really wish they'd give us the ability to set the size of the UI rather than having it trying to guess what the proper size should be and getting it wrong.
