### ISSUE TITLE
Expired certificate crashes Safari

### ISSUE THREAD

**Issue by mattheys** [bitwarden/browser#1872]
## Describe the Bug

Bitwarden 1.49.1 for Safari on Mac (with M1 chip) crashes Safari if you visit a site with an invalid certificate.

## Steps To Reproduce

Visit a site with an invalid or out of date certificate https://expired.badssl.com/

## Expected Result
Safari does not crash

## Actual Result
Safari crashes

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Browser: [e.g. Firefox 73.0.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

## Additional Context

```
Process:               Safari [11093]
Path:                  /Applications/Safari.app/Contents/MacOS/Safari
Identifier:            com.apple.Safari
Version:               14.0.3 (16610.4.3.1.7)
Build Info:            WebBrowser-7610004003001007~5
Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
Responsible:           Safari [11093]
User ID:               501

Date/Time:             2021-06-01 21:42:18.874 +0100
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Anonymous UUID:        6D1470E8-5958-4C2A-A99B-9AC56BCC2791

Sleep/Wake UUID:       AFB4C12B-0DFD-4DD1-922D-666DECF1DE23

Time Awake Since Boot: 94000 seconds
Time Since Wake:       420 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Enabled Web Extensions:
com.bitwarden.desktop.safari (LTZ2PFU5D6) (Version: 1.49.1 - Display Version: 1.49.1) Bitwarden - Free Password Manager
 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '<cert(0x126ed45a0) s: *.badssl.com i: COMODO RSA Domain Validation Secure Server CA> does not conform to NSSecureCoding'
terminating with uncaught exception of type NSException
abort() called
```

**Comment by tgreer-bw** [comment]
Thanks for the report! This issue is actually fixed in the Big Sur 11.3 and higher. Can you update and let us know if the problem continues?

Check out https://github.com/bitwarden/browser/issues/1812 for more info, too.

**Comment by mattheys** [comment]
Sorry not yet had a chance to upgrade but will take your word for it and reopen if its still a problem.
