### ISSUE TITLE
CloudFlare issue in Chromium-based browsers - can't login with Error 1020

### ISSUE THREAD

**Issue by fkrivsky** [bitwarden/browser#2212]
### Steps To Reproduce

1. Have Chromium-based browser (Chrome, Vivaldi, Brave)
2. Go to https://vault.bitwarden.com/#/
3. Enter credentials and click Login

OR

Just try log in using the browser extension.

### Expected Result

Logged in without error.

### Actual Result

Not logged in with error - see screenshot.

### Screenshots or Videos

Brave:
![image](https://user-images.githubusercontent.com/68921465/145180732-b9a82878-65c1-457c-8451-4a6975d481d2.png)

Vivaldi extension:
![image](https://user-images.githubusercontent.com/68921465/145180933-757e7559-613f-4d85-a3ad-193bb071d050.png)

### Additional Context

The problem is NOT reproducible for me in MS Edge browser.

Chrome and Brave browsers have clean install, no non-default extensions. 

**Also, other PC on the same network with the same OS version and browsers seem to log in just fine.**

Similar to https://github.com/bitwarden/browser/issues/1017

### Operating System

Windows

### Operating System Version

Win 10 21H1 build 19043.1348

### Web Browser

Chrome, Brave, Vivaldi

### Browser Version

Vivaldi: 5.0.2497.24 (Stable channel) (64-bit), Brave: Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit), Chrome: Version 96.0.4664.93 (Official Build) (64-bit) / Version 98.0.4754.0 (Official Build) canary (64-bit)

### Build Version

1.54.0

**Comment by si458** [comment]
not sure if this is related to the maintence https://status.bitwarden.com/issues/61af6f0ba8772406a95c45e8
but im having the same issue but with firefox extension and website site too
UK here

**Comment by djsmith85** [comment]
Thank you for your reports and being patient while we resolve this issue.

We would like to apologize for any inconvenience.

We experienced some server glitches this morning and engineering has been working on it. The incident has been resolved and everything should be back to normal. 

**If you are still encountering any issue, please make sure to log out from your account completely and log back in.**

The health status of our services can always be viewed at https://status.bitwarden.com/

**Comment by Doemaas** [comment]
Still happens now, fresh Brave browser Versie 1.32.113 Chromium: 96.0.4664.45 (Officiële build) (x86_64) on macOS 11.6.1. It works correctly on the same machine with Firefox 95.0.

**Comment by si458** [comment]
@Doemaas no issues here, Mac 11.6.1, tried on both chrome and firefox AND websites and extensions? no issues?
have you tried in private window using the vault website https://vault.bitwarden.com ?

**Comment by NicoVadoy** [comment]
On a Win11, with Chrome Version 95.0.4638.54, it does not work via the extension nor via https://vault.bitwarden.com.
both return the error 1020.

**Comment by si458** [comment]
@NicoVadoy works fine here, Edge Version 96.0.1054.43 (Official build) (64-bit) (same as chrome basically)
have you tried updating your chrome version?

**Comment by NicoVadoy** [comment]
@si458, yes, this is a company laptop and I asked to push the latest chrome version they had, which they did. Same happens on the same machine, (Win 10) with Edge (Version 95.0.1020.44 ) and going via https://vault.bitwarden.com.

**Comment by Stikus** [comment]
Can confirm errors - Opera 81.0.4196.60 Win 10 - still don't work via extension and https://vault.bitwarden.com. But standalone client is working.

**Comment by si458** [comment]
no issues here with opera either, just installed it first time as i dont use opera and logged in first time no issues???

**Comment by NicoVadoy** [comment]
For me it is still the same issue. I see twitter users are also reporting more the same issue. 

here is the error I get:
`An error has occurred.
<!DOCTYPE html>     <html class="no-js" lang="en-US">  <head> <title>Access denied | vault.bitwarden.com used Cloudflare to restrict access</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" /> <script defer src="https://api.radar.cloudflare.com/beacon.js"></script> </head> <body> <div id="cf-wrapper"> <div class="cf-alert cf-alert-error cf-cookie-error hidden" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div> <div id="cf-error-details" class="p-0"> <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-15 antialiased"> <h1 class="inline-block md:block mr-2 md:mb-2 font-light text-60 md:text-3xl text-black-dark leading-tight"> <span data-translate="error">Error</span> <span>1020</span> </h1> <span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 6ba6d11f8e7afabc &bull;</span> <span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">2021-12-08 14:52:19 UTC</span> <h2 class="text-gray-600 leading-1.3 text-3xl lg:text-2xl font-light">Access denied</h2> </header> <section class="w-240 lg:w-full mx-auto mb-8 lg:px-8"> <div id="what-happened-section" class="w-1/2 md:w-full"> <h2 class="text-3xl leading-tight font-normal mb-4 text-black-dark antialiased" data-translate="what_happened">What happened?</h2> <p>This website is using a security service to protect itself from online attacks.</p> </div> </section> <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300"> <p class="text-13"> <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6ba6d11f8e7afabc</strong></span> <span class="cf-footer-separator sm:hidden">&bull;</span> <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>:[removed]</span> <span class="cf-footer-separator sm:hidden">&bull;</span> <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span> </p> </div> </div> </div> <script type="text/javascript"> window._cf_translation = {}; </script> </body> </html>`

**Comment by Doemaas** [comment]
@si458 completely fresh Brave, normal and private browser window https://vault.bitwarden.com/#/ and error. Also the same error in Chrome incognito and Opera (82.0.4227.23 (x86_64)). On the same machine no issues with Firefox, Safari. That's why I suspect cert issues with the cloudflare mitm.

**Comment by Cthanatos** [comment]
I'm getting the same issue on my new work machine. I would have posted earlier but I had to use my mobile app to get my Github password and type it in manually.

**Comment by si458** [comment]
@Doemaas have you checked the SSL certificate itself of vault.cloudflare.com?
START Fri, 18 Jun 2021 00:00:00 GMT
END Fri, 17 Jun 2022 23:59:59 GMT
where is everyone located? wonder if its a location issue maybe?

**Comment by NicoVadoy** [comment]
I am located in Oslo, Norway. Not sure where the work proxy goes through though.
Note that on the same machine it works on a Firefox extension

**Comment by NicoVadoy** [comment]
I have another idea. Are people with this issue maybe using ZScaler as their VPN tool?

**Comment by Doemaas** [comment]
@si458 I suspect new cloudflare js code checking the connection. Several connections with certs SNI sni.cloudflaressl.com, cert serial

**Comment by NicoVadoy** [comment]
I have no idea, but I disconnected from VPN (ZScaler), exit zscaler completely, not just log out. Then I was able to login.  
I started ZScaler again and connected to company network and it continues to work.

**Comment by Doemaas** [comment]
@si458 And there is some persistent storage involved in the bitwarden/cloudflare js to check the connection somehow. On the original machine I connected to my private ISP and I could login correctly. Reset the same browser and reconnecting to the first ISP (work) after completely resetting that, I could login correctly. And it seems to be working again. Strange.

**Comment by fkrivsky** [comment]
> I have no idea, but I disconnected from VPN (ZScaler), exit zscaler completely, not just log out. Then I was able to login into Bitwarden.

I got the Zscaler turned off too and am able to connect now.

**Comment by Doemaas** [comment]
Hahaha, it's throwing a hCaptcha at me. In the browser AND the extension. You gotta be kidding me. Never saw that one. Get that out! :)

**Comment by fkrivsky** [comment]
> I have another idea. Are people with this issue maybe using ZScaler as their VPN tool?

I have Zscaler too.
After turning it off I can login again.

**Comment by Doemaas** [comment]
BTW, chromium browsers on iOS still have a (the) problem, login fails with incorrect password. Unable to login via Brave and Opera.

**Comment by Cthanatos** [comment]
Well, I tried again and got the Captcha in the extension, and that worked. Thanks!

**Comment by Stikus** [comment]
Today everything is working again. Thx.

**Comment by djsmith85** [comment]
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Comment by joaofauvel** [comment]
I am having the same issue. Tried disabling zscaler and logging out, cleaning Chrome and other browsers, same error. I'm on the latest 97.0.4692.99.

**Comment by Stikus** [comment]
Can confirm - issue is back.
On vault.bitwarden.com: 
![image](https://user-images.githubusercontent.com/41360525/151811484-e22c3746-1074-4bb1-8044-c85b82536330.png)

In Opera plugin:
![image](https://user-images.githubusercontent.com/41360525/151811578-f1b236e8-2f6e-4812-9601-387232ca09b4.png)


Standalone app is working on same machine.

**Comment by tcaesvk** [comment]
Another case on valult.bitwarden.com:

---

## Please enable cookies.
Error 1020
Ray ID: \<censored\> • 2022-02-03 03:29:38 UTC


### Access denied

### What happened?
This website is using a security service to protect itself from online attacks.

[Cloudflare](https://www.cloudflare.com/5xx-error-landing) Ray ID: **\<censored\>** • Your IP: \<censored\> • Performance & security by Cloudflare

**Comment by mulder21c** [comment]
I am having the same issue. 
It is occurring in both of chrome extension and the login page.

**Comment by mrsshr** [comment]
it seems cloudflare configuration issue.

i do not have access to the following websites:

- https://vault.bitwarden.com/
- https://api.bitwarden.com/
- https://community.bitwarden.com/

**Comment by sneakernuts** [comment]
@Stikus @mulder21c @mrsshr @tcaesvk @joaofauvel curious if you are still having access issues?

**Comment by mulder21c** [comment]
@sneakernuts I think it's fixed.
Currently, the problem is not occurring.

**Comment by mrsshr** [comment]
no problems today.

**Comment by CyrusYen** [comment]
I am seeing the same error on both` vault.bitwarden.com` and the chrome plugin, the OS is Windows 10 and the browser is Chrome 98.0.4758.102.

In the same network, here are the environments that work for me
- Desktop app on windows 10
- Firefox plugin on windows 10
- `vault.bitwarden.com` on mac
- Chrome plugin on mac
- `vault.bitwarden.com` on mobile
- Android app
- IOS app

![image](https://user-images.githubusercontent.com/18083801/154407398-748334e2-93a6-4642-84d5-a8d1a4f79eda.png)

**Comment by tcaesvk** [comment]
@sneakernuts it seems resolved for me now.

**Comment by sneakernuts** [comment]
@CyrusYen what version of the chrome add in do you have?

**Comment by CyrusYen** [comment]
@sneakernuts 1.56.6, but it works well for me now though I am not sure why, thanks.

**Comment by Nierrrrrrr** [comment]
I have same issue under my corporate proxy, I think it will change the certificate which cause the issue. Currently using Chromium 98.0.4758.102. Is there any other way to login?

**Comment by sneakernuts** [comment]
@Nierrrrrrr are you experiencing the same issue in other browsers as well?

**Comment by Nierrrrrrr** [comment]
> @Nierrrrrrr are you experiencing the same issue in other browsers as well?

I'm sorry I can't use another browser to access internet under my corporate proxy, they blocked all internet access except Chrome and Chromium, both experiencing the same issue.

**Comment by sneakernuts** [comment]
@Nierrrrrrr are you still having the same issue today?

**Comment by joaofauvel** [comment]
> @Stikus @mulder21c @mrsshr @tcaesvk @joaofauvel curious if you are still having access issues?

No additional problems on my end since last time reported.

**Comment by Nierrrrrrr** [comment]
> @Nierrrrrrr are you still having the same issue today?

Yes, still the same issue.

**Comment by sneakernuts** [comment]
@Nierrrrrrr would you be able to get in touch with us through our [contact form ](https://bitwarden.com/contact/)and reference this issue? We'll need to gather some more info to assist you. Thanks you!

**Comment by Nierrrrrrr** [comment]
> @Nierrrrrrr would you be able to get in touch with us through our [contact form ](https://bitwarden.com/contact/)and reference this issue? We'll need to gather some more info to assist you. Thanks you!

I submitted through the contact form and reference to this issue. I'll try to give more info you need if possible, thanks!

**Comment by sneakernuts** [comment]
If you need any further assistance please contact our team through our site. Thank you!

**Comment by linsui** [comment]
I encountered this issue today. It seems my ISP is blacklisted by CF.

**Comment by gastonfournier** [comment]
I'm getting access denied (error 1020) when accessing the following urls:
https://vault.bitwarden.com/
https://api.bitwarden.com/

Ray IDs for the two last attempts:
- 73a92cbf993c867a
- 73a92ce90cf9867a

@sneakernuts I can't contact support through the provided contact form as I'm getting a 403 error :disappointed: 
```
Request URL: https://func.bitwarden.com/api/newhelpdeskticket
Request Method: POST
Status Code: 403 
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by gastonfournier** [comment]
> @gastonfournier would you be able to try again? Thanks!

Thanks for your answer! It got resolved sometime during yesterday, I'm not sure if it was a problem with my ISP or something else, because I was able to connect using my phone's mobile network
