### ISSUE TITLE
Windows Hello Not Working with Browser Integration

### ISSUE THREAD

**Issue by dgulik** [bitwarden/browser#2351]

**Comment by Christophe999s** [comment]
Same issue on Mac OS 12.2.1
<img width="1680" alt="Screenshot 2022-02-11 at 14 02 45" src="https://user-images.githubusercontent.com/36367001/153596175-558bf21b-bdcb-4fee-a3b2-36cf03ce49b7.png">

**Comment by cscharf** [comment]
This should be resolved. Can be tested in the meantime using the following build artifacts for browser (we'll cut a release shortly): https://github.com/bitwarden/browser/actions/runs/1829545464

**Comment by gr41nOfS4nd** [comment]
I was having this issue. I resolved it by logging out and removing then reinstalling the extension. Might not be a universal fix but it worked for me.

**Comment by ratva** [comment]
I am still having the same issue (see #1326) despite the update to v1.31.1 of the windows desktop app.
I've tried following the steps from Randrage above, and reinstalling the extension since updating the desktop app but the issue persists for me.

**Comment by Larry-Sussman** [comment]
@ratva Sorry about the trouble here! Our team has worked out and tested a fix: this issue was specific to the browser extension. We've submitted the update to Google for review on the Chrome web store, it will be v1.56.3 when released. When it becomes available [here](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb/related?hl=en), can you please try upgrading your browser plugin to 1.56.3 as well? That should resolve the problem with unlocking with Windows Hello. Hope this helps! 😄

**Comment by alisonbutcher** [comment]
Hey Guys, this still seems to be an issue:
Windows 11 22H2
Bitwarden Desktop 2022.10.1
Bitwarden for Chrome 2022.10.1

**Comment by ratva** [comment]
> @ratva Sorry about the trouble here! Our team has worked out and tested a fix: this issue was specific to the browser extension. We've submitted the update to Google for review on the Chrome web store, it will be v1.56.3 when released. When it becomes available [here](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb/related?hl=en), can you please try upgrading your browser plugin to 1.56.3 as well? That should resolve the problem with unlocking with Windows Hello. Hope this helps! 😄

The previous fix as per this reply from Larry did fix it for me.
 I can confirm that it is still working without issue on 
 Windows 10 22H2
Bitwarden Desktop 2022.10.1
Bitwarden for Chrome 2022.10.1

So perhaps the issue Alison is having relates to the program's behaviour on windows 11.

**Comment by mxbndr** [comment]
I'm having this issue on Version: 2022.12.1, Windows 11 with latest Windows Updates. I can't for the life of me get anything other than the same error here: https://github.com/bitwarden/clients/issues/2351#issuecomment-1036150048

I've tried uninstalling and reinstalling everything, ensuring the registry has the right folders, using different users and accounts. I'm stumped.

**Comment by djsmith85** [comment]
@alisonbutcher, @mxbndr, If you are still experiencing issues, please feel free to get in touch with us, via the [Contact page](https://bitwarden.com/contact). You can include a link to this issue in the message content.

**Comment by ghhv** [comment]
Having just re-installed my Windows OS, I had the same issue and it was resolved by mxbndr's comments above.
