### ISSUE TITLE
firefox plugin - master password is visible in autocomplete field

### ISSUE THREAD

**Issue by gismoranas** [bitwarden/browser#605]
If you set the master password to be visible when you're typing, you can see the password in the autocompletion field (you must have typed it once before of course).

It appears both on the login screen with mail and password and on the login screen with only password.

The chrome plugin has not the same behavior, so it must be a bug.

firefox 59.0.2 (64-bit) on ubuntu 16.04
most recent firefox plugin to date

**Comment by kspearrin** [comment]
This is fixed in next version.

**Comment by begincalendar** [comment]
I have noticed that this is still an issue (at least for me), under the following circumstances:

OS: Ubuntu 16.04 x64
Browser: Firefox 64.0
Bitwarden: 1.37.0

...when using the "Export Vault" feature.

**Comment by kspearrin** [comment]
@begincalendar Thanks for the info. Looks like we missed a spot. Should be fixed in next version.
