### ISSUE TITLE
search function doesn't properly work anymore

### ISSUE THREAD

**Issue by touch444719** [bitwarden/browser#703]
Hello,

I'm running bitwarden Firefox addon (the latest 1.30.3) and I have an issue regarding the search function.

If I have a login name like "example.website.com" and I search for "website" (from the addon search bar), nothing shows up.
If I search for "example" then the result shows up.

It used to work perfectly (I can see you made some changes recently regarding the search function, I guess it's probably related). It works like a charm from the vault search bar, it's only from the firefox addon.

If you can check.

Thank you.

**Comment by kspearrin** [comment]
Should be fixed in 1.30.4

**Comment by touch444719** [comment]
I can see the 1.30.4 is available but the issue is still there sadly.

**Comment by kspearrin** [comment]
What is the URL value of this login?

**Comment by touch444719** [comment]
URL => https://cloud.digitalocean.com/
Name => cloud.digitalocean.com 

If I search on "digital" I don't have any result (It used to work).
If I search "digitalocean" I have the result tho (I didn't notice that before, I never filled the full domain name, sorry about that)

**Comment by kspearrin** [comment]
I added another fix for trailing wildcard searches on URI parts in the next version.

**Comment by touch444719** [comment]
Works again perfectly, thank you !
