### ISSUE TITLE
Clipboard history cleaning Windows 10

### ISSUE THREAD

**Issue by MrZyr0** [bitwarden/browser#939]
Hello,

Since the 1809 version, Windows implement a clipboard history. I've activate the option of Bitwarden to clear clipboard after 15 secondes. But if you have clipboard history activated on he system too, bitwarden will just add "." in the history instead of clear it...

For example, I use bitwarden Opera extension to copy one password. After paste it on another window (and after 15 secondes) I use WIN + V to view the clip board history and I can find "." in first position and in second position my password...

**Comment by kspearrin** [comment]
I don’t know if any way to access the OS clipboard history from browser APIs

**Comment by MrZyr0** [comment]
I have no idea....
I just had a quick look on the internet and it doesn't seem documented...

**Comment by tps125** [comment]
This looks relevant:
https://stackoverflow.com/questions/53190273/bypass-clipboard-history-in-the-windows-10-october-2018-update

**Comment by TD-Solutions** [comment]
The "clear clipboard after N seconds" option under Settings, both on the desktop app and the browser extension, does not clear the pwd from clipboard history, when activated on Windows 10.

## Steps To Reproduce

1. Activate clipboard history
2. Activate bw desktop > settings > Clear clipboard after N seconds
3. Copy any pwd from BW desktop
4. Open Clipboard history (win+v) and see pwd
5. Copy-paste in text editor until delay reached and it is not working anymore
6. Reopen Clipboard history

## Expected Result
The password should have disappeared

## Actual Result

The password is still visible.

## Environment

- Operating system: Win 10, x64
- Build Version: 1.21.0

## Additional Context

Same behaviour when copy pasting from firefox extension.

Related issues:
https://github.com/bitwarden/browser/issues/1047

**Comment by KrisPetkov** [comment]
I can see that his issue is still present. Are there any plans of fixing this?

**Comment by Ozwel** [comment]
Hi, this is something Keepass and LastPass do so there’s no reason Bitwarden couldn’t do this I guess.

It’s quite annoying to go back to clipboard history every time I copy someone from bitwarden. I set the auto erase to 20s but all it does is adding a blank copy in the clipboard. With a simple Win+V I can still see the sensitive information.

here is a picture of the problem: https://prout.ovh/images/2021/04/11/7616c449f73eadb11dd7755501322285.png

Ive posted on Reddit about this too, I’m not alone.

**Comment by arktronic** [comment]
A related issue was reported against [Firefox and KDE Klipper](https://bugzilla.mozilla.org/show_bug.cgi?id=1701974). I imagine this will eventually be solved with an update to the browser extensions clipboard API, but there don't seem to be any decent solutions right now other than disabling the clipboard history functionality entirely.

I would recommend for Bitwarden developers, along with other password manager developers, to push browser makers to extend the WebExtensions API to allow some control over this.

**Comment by chiwou** [comment]
still not solved, the clipboard history is a feature used in our organization, and we can't rollout Bitwarden until this issue is fixed.

Sure we could disable the clipboard history via GPO but we can't remove a well like feature for another app, people will be displeased with the new application (in this case Bitwarden)

**Comment by Gerben321** [comment]
Not solved indeed.
