### ISSUE TITLE
Card autofill fails on bitwarden.com

### ISSUE THREAD

**Issue by mbudde** [bitwarden/browser#983]
When I try to autofill my card on https://vault.bitwarden.com/#/settings/billing I get "02 / 02" filled in the expiration field. What's weird is that none of my card details contains the substring "02" so I'm not sure where it's getting that number from?

**Comment by kspearrin** [comment]
I cannot reproduce. It seems to autofill my card exp correctly. What value do you have set for your card expiration month/year?

**Comment by mbudde** [comment]
I think it's because I'm using a Danish locale. The placeholder text in the expiration field is "MM / ÅÅ". If I change it to "MM / YY" using the devtools, things seems to work correctly.

**Comment by kspearrin** [comment]
Should be fixed next version with https://github.com/bitwarden/browser/commit/103662349fcac4cfaeb45726887393d845f8a664

**Comment by stilettk** [comment]
I still have this issue. I have "March 2022" set in card's settings, and it fills 02/02 on bitwarden.com. Such an irony that I can't pay for bitwarden premium using biitwarden 😊
I'm using Chrome 77.0.3865.90, extension 1.41.0. The website is set to English, and extension is set to russian language (because the extension does not allow to change it 😥)
![image](https://user-images.githubusercontent.com/7068016/65922293-7cad5780-e3ed-11e9-9d52-2b5272168751.png)
![image](https://user-images.githubusercontent.com/7068016/65922230-4f60a980-e3ed-11e9-990f-595186e9a098.png)

**Comment by fabiorzfreitas** [comment]
I'm having this issue with auto fill expiration dates as well. I'm pretty sure is locale-related. Most Brazilian (.br) websites use MM/YY for expiration date. Even if I set the year to, say, "28", Bitwarden will change it to "2028", which means it will try to fill the expiration date using MM/YYYY oi YYYY/MM, I'm not sure what's the default.

I think the solution for this would be adding a setting to allow users to set Card Autofill settings based on country. I don't think you should research every country's method, but allowing the user to input something like: 

Domains: .br
Exp Date Format: drop-down menu with the different date formats, maybe even adding a Custom, or leave it all to the user to input the Ms and Ys..

Thank you

**Comment by djsmith85** [comment]
@fabiorzfreitas This [PR](https://github.com/bitwarden/clients/pull/5700) might be related to your issue

**Comment by fabiorzfreitas** [comment]
@djsmith85 it seems that it already has been reviewed and approved, so I just have to wait for the merge, right? I subscribed to that PR, thanks!
